# Window Customization
window:
  dimensions:
    columns: 140
    lines: 38
  padding:
    x: 15
    y: 15
  decorations: none
scrolling:
  history: 10000
  multiplier: 3
background_opacity: 1.0
dynamic_title: true

# Font Customization
font:
  normal:
    family: FiraCode Nerd Font
    style: Retina
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Italic
  size: 13.25
  offset:
    x: 0
    y: 1
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: false
  debug:
    persistent_logging: false
draw_bold_text_with_bright_colors: true
schemes:
# Colors (Snazzy)
  Snazzy: &Snazzy
    # Default colors
    primary:
      background: '#282a36'
      foreground: '#eff0eb'

    # Normal colors
    normal:
      black:   '#282a36'
      red:     '#ff5c57'
      green:   '#5af78e'
      yellow:  '#f3f99d'
      blue:    '#57c7ff'
      magenta: '#ff6ac1'
      cyan:    '#9aedfe'
      white:   '#f1f1f0'

    # Bright colors
    bright:
      black:   '#686868'
      red:     '#ff5c57'
      green:   '#5af78e'
      yellow:  '#f3f99d'
      blue:    '#57c7ff'
      magenta: '#ff6ac1'
      cyan:    '#9aedfe'
      white:   '#f1f1f0'
  # Colors (One Dark)
  One_Dark: &One_Dark
    # Default colors
    primary:
      background: '#282c34'
      foreground: '#abb2bf'

    # Normal colors
    normal:
      # NOTE: Use '#131613' for the `black` color if you'd like to see
      # black text on the background.
      black:   '#282c34'
      red:     '#e06c75'
      green:   '#98c379'
      yellow:  '#d19a66'
      blue:    '#61afef'
      magenta: '#c678dd'
      cyan:    '#56b6c2'
      white:   '#abb2bf'

    # Bright colors
    bright:
      black:   '#5c6370'
      red:     '#e06c75'
      green:   '#98c379'
      yellow:  '#d19a66'
      blue:    '#61afef'
      magenta: '#c678dd'
      cyan:    '#56b6c2'
      white:   '#ffffff'
colors: *Snazzy
#colors: *One_Dark
# Color Settings (Gruvbox)
#colors:
#  primary:
#    background: '#1d2021'
#    foreground: '#ebdbb2'

#  normal:
#    black:   '#282828'
#    red:     '#cc241d'
#    green:   '#98971a'
#    yellow:  '#d79921'
#    blue:    '#458588'
#    magenta: '#b16286'
#    cyan:    '#689d6a'
#    white:   '#a89984'

#  bright:
#    black:   '#928374'
#    red:     '#fb4934'
#    green:   '#b8bb26'
#    yellow:  '#fabd2f'
#    blue:    '#83a598'
#    magenta: '#d3869b'
#    cyan:    '#8ec07c'
#    white:   '#ebdbb2'

#  selection:
#    text: '0xffffff'
#    background: '0xdc3232'
#    white:   '0xffffff'
cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
  - { key: N, mods: Command, action: SpawnNewInstance }

#||\\ //||
#|| \// || Mackenzie Criswell
#|| //\ || https://makc.co
#||   \\|| https://github.com/makccr

